; Dominic Beesley, 2005
; Mark Fisher, 2026
;

OSFile_Save                     =       0
OSFile_Write                    =       1
OSFile_WriteLoad                =       2
OSFile_WriteExec                =       3
OSFile_WriteAttr                =       4
OSFile_Read                     =       5
OSFile_Delete                   =       6
OSFile_Load                     =       255

OSFile_NotFound                 =       $0
OSFile_IsFile                   =       $1
OSFile_IsDir                    =       $2
OSFile_IsImage                  =       $3
OSFile_FileTypeShift            =       8