;
; ca65 Assembler include file for BBC Micro OSGBPB constants.
; (c) Dominic Beesley 2005
;

OSGBPB_WriteAt                  =       $1
OSGBPB_Write                    =       $2
OSGBPB_ReadAt                   =       $3
OSGBPB_Read                     =       $4
OSGBPB_ReadDiscName             =       $5
OSGBPB_ReadCSDName              =       $6
OSGBPB_ReadLibName              =       $7
OSGBPB_CSDEntries               =       $8
OSGBPB_DirEntries               =       $9